In [7]:
import numpy as np

## One-Dimensional Matrix

In [8]:
zeroarray = np.arange(10)  #arange works like range function for array

In [9]:
zeroarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Matrix initialisation

In [10]:
zeromatrix = np.zeros(shape=(3,3))

In [11]:
zeromatrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Matrix Operations

In [12]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
l2 = [[2,4,6],[8,10,12],[14,16,18]]

A = np.array(l1)
B = np.array(l2)

In [13]:
C = 3*A + B
C

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
D = np.matmul(A,B)
D

array([[ 60,  72,  84],
       [132, 162, 192],
       [204, 252, 300]])